package com.abcdabcd987.compiler2016;

/**
 * Created by abcdabcd987 on 2016-03-02.
 */
public enum TokenType {
    IDENTIFIER, // foo, bar, ...
    KEYWORD,    // if, while, ...
    SYMBOL,     // + - * / ...
    INTEGER,    // 123, ...
    DOUBLE,     // 0.123, ...
    CHAR,       // 'a', ...
    STRING,     // "str", ...
    EOF         // end-of-file
}
